Samples/BlocklySample/Resources/Turtle/toolbox.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/245)
=> Removed infinite loop block from turtle

Blockly.podspec, Source/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/247)
=> Updated project and podspec to v0.5.0

Source/Layout/LayoutConfig.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/264)
=> Rearranged method signatures in LayoutConfig

Blockly.podspec, CHANGELOG.md, Source/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/267)
=> Increasing the version to 0.5.1.

Source/Control/NameManager.swift, Source/Layout/FieldVariableLayout.swift, Source/Model/FieldVariable.swift, Tests/Source/Control/NameManagerTest.swift, Tests/Source/Model/WorkspaceTest.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/270)
=> Fixing up NameManager so it follows web functionality more closely.

Blockly.xcodeproj/project.pbxproj, Source/Layout/FieldVariableLayout.swift, Source/Layout/WorkspaceLayoutCoordinator.swift, Source/Model/FieldVariable.swift, Source/Model/Workspace.swift, Source/UI/View Controllers/VariableNameViewController.swift, Source/UI/Views/FieldVariableView.swift, Tests/Source/Model/FieldVariableTest.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/271)
=> Moving NameManager to the Layout level, rather than the Model level.

Source/Model/BlockBuilder.swift, Source/Model/InputBuilder.swift, Tests/Source/Control/ConnectionManagerTest.swift, Tests/Source/Layout/BlockLayoutTest.swift, Tests/Source/Model/JSON/InputJSONTest.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/280)
=> Renamed InputBuilder's build() to makeInput()

Samples/BlocklySample/Resources/SimpleWorkbench/toolbox_basic.xml, Samples/BlocklySample/Resources/Turtle/toolbox.xml, Source/Model/Toolbox.swift, Source/Model/XML/Toolbox+XML.swift, Source/UI/View Controllers/ToolboxCategoryListViewController.swift, Source/UI/View Controllers/ToolboxCategoryViewController.swift, Source/UI/View Controllers/WorkbenchViewController.swift, Source/UI/Views/FieldVariableView.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/283)
=> Adding the UI for adding variables

Source/Control/BlockBumper.swift, Source/Control/DefaultConnectionValidator.swift, Source/Layout/Default/DefaultBlockLayout+Background.swift, Source/Layout/Default/DefaultInputLayout.swift, Source/Layout/WorkspaceLayoutCoordinator.swift, Source/Model/Connection.swift, Source/Model/Input.swift, Tests/Source/Model/ConnectionTest.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/285)
=> Fixed sourceBlock and sourceInput on Input/Connection to be optionals

Blockly.xcodeproj/project.pbxproj, Samples/BlocklySample/Code/AllFieldsWorkbenchViewController.swift, Samples/BlocklySample/Code/SimpleWorkbenchViewController.swift, Samples/BlocklySample/Code/TurtleObjCViewController.m, Samples/BlocklySample/Code/TurtleSwiftViewController.swift, Samples/BlocklySample/Resources/SimpleWorkbench/toolbox_basic.xml, Samples/BlocklySample/Resources/Turtle/toolbox.xml, Source/Layout/FieldVariableLayout.swift, Source/Layout/LayoutConfig.swift, Source/Layout/ToolboxLayout.swift, Source/Layout/WorkspaceLayoutCoordinator.swift, Source/Model/FieldVariable.swift, Source/Model/Toolbox.swift, Source/Model/Workspace.swift, Source/UI/View Controllers/ToolboxCategoryViewController.swift, Source/UI/View Controllers/TrashCanViewController.swift, Source/UI/View Controllers/WorkbenchViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/286)
=> Adding the dynamic variable category for the toolbox.

Source/UI/View Controllers/ToolboxCategoryViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/294)
=> Fixed bad merge

Blockly.xcodeproj/project.pbxproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/297)
=> Second bad merge fix

Blockly.xcodeproj/project.pbxproj, Samples/BlocklySample/Resources/SimpleWorkbench/toolbox_basic.xml, Source/Layout/Default/DefaultLayoutFactory.swift, Source/Layout/LayoutConfig.swift, Source/Layout/LayoutEngine.swift, Source/Layout/MutatorProcedureDefinitionLayout.swift, Source/Model/JSON/BlockJSONFile.swift, Source/Model/MutatorProcedureDefinition.swift, Source/Model/XML/Toolbox+XML.swift, Source/UI/Views/FieldDropdownView.swift, Source/UI/Views/FieldVariableView.swift, Source/UI/Views/MutatorProcedureDefinitionView.swift, Source/UI/Views/ViewFactory.swift
- Updated set of default blocks created for procedure toolbox category
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/295)
=> - Added mutator for editing procedure definition blocks

Blockly.xcodeproj/project.pbxproj, Resources/Default/procedure_blocks.json, Source/Layout/Default/DefaultLayoutFactory.swift, Source/Layout/MutatorProcedureCallerLayout.swift, Source/Model/JSON/BlockJSONFile.swift, Source/Model/MutatorProcedureCaller.swift, Source/Model/XML/Toolbox+XML.swift, Source/UI/Views/MutatorProcedureDefinitionView.swift
- Fixed bug with reordering parameters for the procedure definition mutator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/299)
=> - Added mutator for procedure callers

Blockly.xcodeproj/project.pbxproj, Source/Common/WeakSet.swift, Source/Control/NameManager.swift, Source/Control/ProcedureCoordinator.swift, Source/Layout/MutatorProcedureDefinitionLayout.swift, Source/Layout/WorkspaceLayoutCoordinator.swift, Source/Model/FieldLabel.swift, Source/Model/MutatorProcedureDefinition.swift, Source/Model/Workspace.swift, Source/Model/XML/Toolbox+XML.swift, Source/UI/View Controllers/ToolboxCategoryViewController.swift, Source/UI/View Controllers/WorkbenchViewController.swift, Source/UI/Views/MutatorProcedureDefinitionView.swift, Tests/Source/Control/NameManagerTest.swift, Tests/Source/Layout/BlockGroupLayoutTest.swift
- Added method to NameManager for renaming existing name with new case sensitivty
- Fixed ToolboxCategoryViewController logic for how it was creating variable blocks
- Allowed copied blocks to have their position set immediately on creation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/307)
=> - Added procedure functionality

Resources/CodeGenerator/code_generator_mutators.js, Samples/BlocklySample/Resources/Turtle/toolbox.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/309)
=> - Added code generation support for procedure blocks

Blockly.xcodeproj/project.pbxproj, Source/Control/ProcedureCoordinator.swift, Source/Layout/Default/DefaultLayoutFactory.swift, Source/Layout/Layout.swift, Source/Layout/MutatorProcedureIfReturnLayout.swift, Source/Layout/WorkspaceLayoutCoordinator.swift, Source/Model/JSON/BlockJSONFile.swift, Source/Model/MutatorProcedureIfReturn.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/312)
=> Added support for procedure if-return block

Source/Model/JSON/Field+JSON.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/317)
=> Fixed Xcode warning for Field+JSON

Blockly.xcodeproj/project.pbxproj, Resources/Default/logic_blocks.json, Resources/Default/procedure_blocks.json, Source/Common/BlocklyError.swift, Source/Model/Block.swift, Source/Model/BlockBuilder.swift, Source/Model/BlockExtension.swift, Source/Model/BlockFactory.swift, Source/Model/JSON/Block+JSON.swift, Source/Model/JSON/BlockJSONFile.swift
- Updated block JSON for mutator blocks to use extensions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/318)
=> - Implemented Block extensions

Blockly.xcodeproj/project.pbxproj, Source/Common/BlocklyError.swift, Source/Model/Event/BlocklyEvent.swift, Source/Model/Event/BlocklyEventFactory.swift, Source/Model/Event/BlocklyUIEvent.swift, Source/Model/Event/ChangeEvent.swift, Source/Model/Event/CreateEvent.swift, Source/Model/Event/DeleteEvent.swift, Source/Model/Event/MoveEvent.swift, Source/Model/Workspace.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/320)
=> Added model objects for events

Blockly.xcodeproj/project.pbxproj, Samples/BlocklySample/Code/AllFieldsWorkbenchViewController.swift, Samples/BlocklySample/Code/SimpleWorkbenchViewController.swift, Samples/BlocklySample/Code/TurtleObjCViewController.m, Samples/BlocklySample/Code/TurtleSwiftViewController.swift, Source/Control/EventManager.swift, Source/Layout/WorkspaceLayoutCoordinator.swift, Source/UI/View Controllers/WorkbenchViewController.swift
- Changed WorkbenchViewController to force usage of a BlockFactory
- Added undo/redo to workbench, and implemented it for create events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/322)
=> - Added EventManager, which is responsible for collecting/firing events

Source/Control/Dragger.swift, Source/Control/EventManager.swift, Source/Control/MutatorHelper.swift, Source/Layout/BlockGroupLayout.swift, Source/Layout/LayoutBuilder.swift, Source/Layout/MutatorIfElseLayout.swift, Source/Layout/MutatorProcedureCallerLayout.swift, Source/Layout/MutatorProcedureDefinitionLayout.swift, Source/Layout/MutatorProcedureIfReturnLayout.swift, Source/Layout/WorkspaceLayoutCoordinator.swift, Source/Model/Connection.swift, Source/Model/Event/DeleteEvent.swift, Source/Model/Event/MoveEvent.swift, Source/UI/View Controllers/WorkbenchViewController.swift, Tests/Source/Layout/LayoutBuilderTest.swift, Tests/Source/Layout/WorkspaceLayoutCoordinatorTest.swift
- Changed undo of CreateEvent to delete instead of move to trash
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/323)
=> - Implemented delete/move events.

Source/Layout/BlockLayout.swift, Source/Layout/FieldAngleLayout.swift, Source/Layout/FieldCheckboxLayout.swift, Source/Layout/FieldColorLayout.swift, Source/Layout/FieldDateLayout.swift, Source/Layout/FieldDropdownLayout.swift, Source/Layout/FieldInputLayout.swift, Source/Layout/FieldLayout.swift, Source/Layout/FieldNumberLayout.swift, Source/Layout/FieldVariableLayout.swift, Source/Layout/Layout.swift, Source/Layout/MutatorIfElseLayout.swift, Source/Layout/MutatorLayout.swift, Source/Layout/MutatorProcedureCallerLayout.swift, Source/Layout/MutatorProcedureDefinitionLayout.swift, Source/Layout/MutatorProcedureIfReturnLayout.swift, Source/Model/Block.swift, Source/Model/Event/ChangeEvent.swift, Source/Model/FieldVariable.swift, Source/Model/MutatorIfElse.swift, Source/Model/MutatorProcedureCaller.swift, Source/Model/MutatorProcedureDefinition.swift, Source/Model/MutatorProcedureIfReturn.swift, Source/Model/ProcedureParameter.swift, Source/UI/View Controllers/WorkbenchViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/328)
=> Implemented change events for fields/mutators

Source/Control/EventManager.swift, Source/Model/Event/BlocklyEventFactory.swift, Source/Model/JSON/Field+JSON.swift, Source/UI/Views/ViewManager.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/337)
=> Privatized initializers for singletons

Source/Common/DropdownView.swift, Source/Layout/LayoutConfig.swift, Source/UI/View Controllers/DropdownOptionsViewController.swift, Source/UI/Views/FieldAngleView.swift, Source/UI/Views/FieldDateView.swift, Source/UI/Views/FieldDropdownView.swift, Source/UI/Views/FieldInputView.swift, Source/UI/Views/FieldLabelView.swift, Source/UI/Views/FieldNumberView.swift, Source/UI/Views/FieldVariableView.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/336)
=> Adding configurable font colors.

Samples/BlocklySample.xcodeproj/xcshareddata/xcschemes/BlocklySample (Release - RTL).xcscheme, Samples/BlocklySample.xcodeproj/xcshareddata/xcschemes/BlocklySample (Release).xcscheme, Tests/Source/Model/XML/BlockXMLTest.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/339)
=> Fixed tests and added schemes for release builds

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/346)
=> Add developer forum and registration links

Blockly.podspec, CHANGELOG.md, README.md, Samples/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/357)
=> Versioned off at v0.7

Samples/BlocklySample/Sources/TurtleSwiftViewController.swift, Sources/Common/CodeGenerator.swift, Sources/Common/ObjectPool.swift, Sources/Layout/LayoutConfig.swift, Sources/Model/Connection.swift, Sources/Model/FieldNumber.swift, Sources/UI/View Controllers/ToolboxCategoryListViewController.swift, Sources/UI/View Controllers/WorkbenchViewController.swift, Sources/UI/Views/Default/DefaultBlockView+Render.swift, Sources/UI/Views/ViewManager.swift, Tests/Sources/XCTestCase+Helper.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/359)
=> Fixes compile errors/warnings related to Swift 3.1

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/360)
=> Versioned off at v0.7.1

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/Info.plist, Samples/BlocklySample/Sources/TurtleSwiftViewController.swift, Sources/Common/CodeGenerator.swift, Sources/Common/ObjectPool.swift, Sources/Info.plist, Sources/Layout/LayoutConfig.swift, Sources/Model/Connection.swift, Sources/Model/FieldNumber.swift, Sources/UI/View Controllers/ToolboxCategoryListViewController.swift, Sources/UI/View Controllers/WorkbenchViewController.swift, Sources/UI/Views/Default/DefaultBlockView+Render.swift, Sources/UI/Views/ViewManager.swift, Tests/Sources/XCTestCase+Helper.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/361)
=> Merging develop into master

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/363)
=> Versioned off at v0.7.2

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/Info.plist, Sources/Info.plist, Sources/Model/JSON/Field+JSON.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/364)
=> Merge develop into master

Samples/BlocklySample/Sources/TurtleObjCViewController.m, Samples/BlocklySample/Sources/TurtleSwiftViewController.swift, Sources/Common/CodeGeneratorService.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/365)
=> Changes code generator service to include request UUID on callbacks

Blockly.podspec, CHANGELOG.md, Cartfile.resolved, Samples/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/371)
=> Versioning off to 0.7.4

CONTRIBUTING.md
Remove the spaces to make linking works
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/375)
=> Fix markdown syntax

Sources/Common/CodeGeneratorService.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/374)
=> Cleans up documentation for CodeGeneratorService

Blockly.xcodeproj/xcshareddata/xcschemes/BlocklyTests.xcscheme
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/387)
=> Re-adds test target for Blockly

Sources/Control/Dragger.swift, Sources/Layout/BlockGroupLayout.swift, Sources/Layout/WorkspaceLayoutCoordinator.swift, Sources/Model/Event/BlocklyEvent+Move.swift, Sources/UI/View Controllers/ToolboxCategoryViewController.swift, Sources/UI/Views/FieldVariableView.swift
- Removed use of BlocklyEvent.BlockMove as it could cause unnecessary Block retains
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/388)
=> - Fixed memory leak with variable dialogs

Sources/Control/Dragger.swift, Sources/Control/EventManager.swift, Sources/Control/ProcedureCoordinator.swift, Sources/Layout/BlockGroupLayout.swift, Sources/Layout/BlockLayout.swift, Sources/Layout/FieldLayout.swift, Sources/Layout/MutatorLayout.swift, Sources/Layout/MutatorProcedureIfReturnLayout.swift, Sources/Layout/WorkspaceLayoutCoordinator.swift, Sources/Model/Event/BlocklyEventFactory.swift, Sources/Model/JSON/Field+JSON.swift, Sources/UI/View Controllers/WorkbenchViewController.swift, Sources/UI/Views/FieldAngleView.swift, Sources/UI/Views/FieldCheckboxView.swift, Sources/UI/Views/FieldColorView.swift, Sources/UI/Views/FieldDateView.swift, Sources/UI/Views/FieldDropdownView.swift, Sources/UI/Views/FieldInputView.swift, Sources/UI/Views/FieldNumberView.swift, Sources/UI/Views/FieldVariableView.swift, Sources/UI/Views/LayoutView.swift, Sources/UI/Views/MutatorIfElseView.swift, Sources/UI/Views/MutatorProcedureDefinitionView.swift, Sources/UI/Views/ViewBuilder.swift, Sources/UI/Views/ViewManager.swift, Sources/UI/Views/WorkspaceView.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/389)
=> Renames singletons of `sharedInstance` to `shared`

Sources/UI/View Controllers/ToolboxCategoryViewController.swift, Sources/UI/Views/FieldVariableView.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/391)
=> Trims variable names on add/rename

Sources/Model/Workspace.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/395)
=> Fixes error message to correctly show UUID

README.md
Makes the registration link one we can redirect in case we change forms in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/399)
=> Update the registration link

Sources/Common/UIView+Helper.swift, Sources/UI/Views/MutatorProcedureDefinitionView.swift
- no longer jumps around when adding/editing parameters
- bug fix when reordering a parameter
- bug fix when adding a parameter out of view
- changed popover resizing to be less aggressive
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/398)
=> Fixes for the procedure definition mutator:

Samples/BlocklySample/BlocklySample.xcodeproj/xcshareddata/xcschemes/BlocklySample.xcscheme, Sources/Control/ConnectionManager.swift, Sources/Layout/Default/DefaultBlockLayout.swift, Sources/Layout/Default/DefaultInputLayout.swift, Sources/Layout/InputLayout.swift, Sources/Layout/Layout.swift, Sources/Layout/LayoutConfig.swift, Sources/Model/Block.swift, Sources/Model/Connection.swift, Sources/Model/Input.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/401)
=> Performance improvements

Sources/Control/EventManager.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/402)
=> Stops events from being added to the event queue if they're discardable

Sources/Common/DropdownView.swift, Sources/UI/Views/FieldDropdownView.swift, Sources/UI/Views/FieldVariableView.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/403)
=> Fixes dropdown arrow to match workspace scaling

Blockly.podspec, CHANGELOG.md, README.md, Samples/BlocklyCodeLab/README.md, Samples/BlocklySample/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/405)
=> Versioned off at v1.0

Blockly.podspec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/407)
=> Fixing the podspec so it properly references the version number.

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/408)
=> Merge "develop" into "master"

Sources/UI/View Controllers/WorkbenchViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/412)
=> Fixes bug with undo/redo buttons that causes crashing in iOS 8.x

Sources/Layout/Default/DefaultBlockLayout.swift, Sources/Layout/Default/DefaultInputLayout.swift, Sources/Layout/Default/DefaultLayoutConfig.swift, Sources/UI/PathHelper.swift, Sources/UI/Views/Default/DefaultBlockView.swift, Sources/UI/WorkspaceBezierPath.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/419)
=> - Adds rounded corners to block rendering

Sources/Common/ColorPalette.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/427)
=> Makes ColorPalette available in obj-c

Blockly.podspec, CHANGELOG.md, README.md, Samples/BlocklySample/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/430)
=> Versioned off at v1.1

Sources/UI/View Controllers/WorkbenchViewController.swift, Sources/UI/View Controllers/WorkspaceViewController.swift
- Fixes layer ordering of trash can folder view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/433)
=> - Fixes bug with popovers potentially dismissing WorkbenchViewController

Sources/ObjC/Blockly.h, Tests/Sources/Core/Common/CodeGeneratorServiceTest.swift, Tests/Sources/XCTestCase+Helper.swift
- Removes unnecessary test code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/440)
=> - Fixes Obj-C compilation error where WebKit protocol can't be found

Sources/UI/View Controllers/ToolboxCategoryViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/441)
=> Fixes bug where the same variable block can be created multiple times

Samples/BlocklySample/BlocklySample/Sources/TurtleObjCViewController.m, Samples/BlocklySample/BlocklySample/Sources/TurtleSwiftViewController.swift, Sources/UI/View Controllers/WorkbenchViewController.swift, Sources/UI/Views/WorkspaceView.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/442)
=> Adds method to set viewport of workspace

Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/generators.js, Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/toolbox.xml, Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle_blocks.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/443)
=> Updates turtle demo to use angle picker

Samples/BlocklySample/BlocklySample.xcodeproj/project.pbxproj, Samples/BlocklySample/BlocklySample/Sources/FileHelper.swift, Samples/BlocklySample/BlocklySample/Sources/TurtleObjCViewController.m, Samples/BlocklySample/BlocklySample/Sources/TurtleSwiftViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/444)
=> Adds save/load functionality to turtle demo

Blockly.xcodeproj/xcshareddata/xcschemes/BlocklyTests.xcscheme, Samples/BlocklySample/BlocklySample/Resources/Non-Localized/SimpleWorkbench/test.xml, Sources/Layout/Layout.swift, Sources/UI/View Controllers/ToolboxCategoryViewController.swift, Sources/UI/View Controllers/WorkbenchViewController.swift, Tests/Sources/Layout/LayoutTest.swift
- Adds missing calls to fire pending events in EventManager
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/446)
=> - Optimizes Layout.flattenedLayoutTree()

Sources/Layout/Default/DefaultBlockLayout+Background.swift, Sources/Layout/Default/DefaultBlockLayout.swift, Sources/Layout/Default/DefaultLayoutConfig.swift, Sources/Layout/LayoutConfig.swift, Sources/Model/Block.swift, Sources/Model/BlockBuilder.swift, Sources/Model/JSON/Block+JSON.swift, Sources/UI/PathHelper.swift, Sources/UI/Views/Default/DefaultBlockView.swift, Tests/Resources/block_json_test.json, Tests/Sources/Core/Common/CodeGeneratorServiceTest.swift, Tests/Sources/Model/JSON/BlockJSONTest.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/449)
=> Allows individual hats per blocks

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/455)
=> Versioned off at v1.1.2

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/466)
=> Versioning off at v1.1.3

Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.html, Samples/BlocklySample/BlocklySample/Resources/Non-Localized/Turtle/turtle.js, Samples/BlocklySample/BlocklySample/Sources/TurtleObjCViewController.h, Samples/BlocklySample/BlocklySample/Sources/TurtleObjCViewController.m, Samples/BlocklySample/BlocklySample/Sources/TurtleSwiftViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/470)
=> Changing the turtle demo so the canvas resizes to match what the turtle draws.

Sources/UI/Views/WorkspaceView.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/476)
=> Fixes bug where zooming in RTL causes a jump in the workspace viewport

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/482)
=> Versioned off at v1.2

Sources/Control/ProcedureCoordinator.swift, Sources/Model/Event/BlocklyEvent+Change.swift, Sources/Model/Event/BlocklyEvent+UI.swift, Sources/Model/Event/BlocklyEvent.swift, Sources/Model/Event/BlocklyEventFactory.swift, Sources/UI/View Controllers/WorkbenchViewController.swift
- Refactors BlocklyEvent.Change and BlocklyEvent.UI so custom elements can be specified by outside developers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/484)
=> - Opens BlocklyEvent and BlocklyEventFactory so they can be subclassed

Sources/UI/View Controllers/WorkbenchViewController.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/489)
=> Opens event stack code in WorkbenchViewController to allow for developer customization

Sources/Common/ColorHelper.swift, Sources/Model/FieldDate.swift, Sources/Model/FieldNumber.swift, Sources/UI/Views/NumberPad.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/492)
=> Removes use of deprecated characters property on strings

Sources/Model/FieldCheckbox.swift, Tests/Sources/Model/XML/BlockXMLTest.swift, Tests/Sources/Model/XML/FieldXMLTest.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/494)
=> Fixes FieldCheckbox to serialize value to TRUE/FALSE

Blockly.podspec, CHANGELOG.md, Cartfile, Samples/BlocklySample/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/496)
=> Versioned off at v1.2.1

Blockly.podspec, CHANGELOG.md, Samples/BlocklySample/BlocklySample/Info.plist, Sources/Info.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/501)
=> Versioned off at v1.2.2

CHANGELOG.md, Sources/Layout/LayoutHelper.swift
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-ios/505)
=> Fixed Spelling.
